### ISSUE TITLE
Examples are not functioning

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/variable-fonts-info-site#100]
> Is there a trick to making these experiments works? I can get size to change but see nothing when I adjust opsz or weight
>
> Eg https://variablefonts.typenetwork.com/examples/styles/roboto-instances-vs-interpolated#

Adjusting CSS values in Chrome on Android didn't work for anything.

**Comment by chrissam42** [comment]
This problem is specific to the Roboto instances demo, because it has some custom Javascript to adjust the weights depending on the viewport size. I specifically added the ability of the experiment popup to run scripts in the HTML to make this one work, but I think the simplest solution is to remove that and let the demo wrap poorly on narrower screens.

**Comment by chrissam42** [comment]
I've disabled including Javascript in the playground for now. I believe this is the only example it affects.

**Comment by chrissam42** [comment]
Related to this, Roboto doesn't have an opsz axis, which is included in this example for some reason. Could switch to Roboto Delta?

**Comment by dberlow** [comment]
Can’t switch right now.

On Jun 25, 2019, at 12:13 PM, Chris Lewis <notifications@github.com> wrote:

Related to this, Roboto doesn't have an opsz axis, which is included in this example for some reason. Could switch to Roboto Delta?
